# Generated by Django 3.0.3 on 2020-02-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_simple_describe', models.CharField(max_length=200)),
                ('movie_detailed_describe', models.TextField()),
                ('movie_link', models.URLField()),
                ('movie_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
