# Generated by Django 3.0.3 on 2020-02-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wamt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
