# Generated by Django 3.0.3 on 2020-02-20 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('wamt', '0003_event_groupevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupEvents',
            new_name='GroupEvent',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_vote_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='end vote time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_vote_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='start vote time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='event time'),
        ),
    ]
