# Generated by Django 3.0.3 on 2020-02-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('wamt', '0004_auto_20200220_0236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupEvent',
            new_name='GroupEventManager',
        ),
    ]
